version: "3"

volumes:
  mysql-volume:
  golang-volume:
  frontend-node_modules:

services:
  golang:
    build: app
    ports:
      - 80:80
    volumes:
      - ./app:/workspace
      - golang-volume:/go
    working_dir: /workspace
    env_file:
      - ./.env
  frontend:
    build: frontend
    ports:
      - 8000:8000
      - 8080:8080
    volumes:
      - ./frontend:/workspace
      - frontend-node_modules:/workspace/node_modules
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
    env_file:
      - ./.env
