openapi: 3.1.0
info:
  title: simple-auth
  version: '1.0'
  contact:
    name: dummy
  description: シンプルな認証システム
servers:
  - url: 'http://localhost:80'
paths:
  /v1/auth:
    post:
      summary: 認証
      operationId: post-v1-auth
      responses:
        '200':
          $ref: '#/components/responses/ResponseAuth'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
      description: ユーザー名、パスワードで認証
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestAuth'
        description: ''
  /v1/verify:
    post:
      summary: ''
      operationId: post-v1-verify
      responses:
        '200':
          $ref: '#/components/responses/ResponseVerify'
      description: クエリパラメータのtokenが有効なトークンかチェック
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestVerify'
components:
  schemas:
    RequestAuth:
      title: RequestAuth
      type: object
      description: 認証リクエストボディ
      properties:
        email:
          type: string
          description: メールアドレス
        password:
          type: string
          description: パスワード
      required:
        - email
        - password
    RequestVerify:
      title: RequestVerify
      type: object
      description: トークン検証リクエストボディ
      properties:
        token:
          type: string
          description: トークン
      required:
        - token
    VerifyUser:
      title: VerifyUser
      type: object
      properties:
        id:
          type: string
          description: ユーザーID
        email:
          type: string
          description: メールアドレス
      required:
        - id
        - email
      description: 認証されたユーザー
  responses:
    ResponseAuth:
      description: 認証成功応答
      content:
        application/json:
          schema:
            type: object
            properties:
              token:
                type: string
                description: 認証トークン
              expired_at:
                type: integer
                description: 認証トークンの有効期限Unixtimeミリ秒
            required:
              - token
              - expired_at
    ResponseVerify:
      description: 認証成功のレスポンス
      content:
        application/json:
          schema:
            type: object
            properties:
              user:
                $ref: '#/components/schemas/VerifyUser'
            required:
              - user
  parameters: {}
tags:
  - name: adapter
