// Package adapter provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package adapter

// 認証リクエストボディ
type RequestAuth struct {
	// メールアドレス
	Email string `json:"email"`

	// パスワード
	Password string `json:"password"`
}

// トークン検証リクエストボディ
type RequestVerify struct {
	// トークン
	Token string `json:"token"`
}

// 認証されたユーザー
type VerifyUser struct {
	// メールアドレス
	Email string `json:"email"`

	// ユーザーID
	Id string `json:"id"`
}

// ResponseAuth defines model for ResponseAuth.
type ResponseAuth struct {
	// 認証トークンの有効期限Unixtimeミリ秒
	ExpiredAt int `json:"expired_at"`

	// 認証トークン
	Token string `json:"token"`
}

// ResponseVerify defines model for ResponseVerify.
type ResponseVerify struct {
	// 認証されたユーザー
	User VerifyUser `json:"user"`
}

// PostV1AuthJSONBody defines parameters for PostV1Auth.
type PostV1AuthJSONBody RequestAuth

// PostV1VerifyJSONBody defines parameters for PostV1Verify.
type PostV1VerifyJSONBody RequestVerify

// PostV1AuthJSONRequestBody defines body for PostV1Auth for application/json ContentType.
type PostV1AuthJSONRequestBody PostV1AuthJSONBody

// PostV1VerifyJSONRequestBody defines body for PostV1Verify for application/json ContentType.
type PostV1VerifyJSONRequestBody PostV1VerifyJSONBody

