// Package OpenApi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package adapter

// 認証リクエストボディ
type RequestPostAuth struct {
	// パスワード
	Password string `json:"password"`

	// メールアドレス
	Email string `json:"email"`
}

// Token defines model for token.
type Token string

// ResponsePostAuth defines model for ResponsePostAuth.
type ResponsePostAuth struct {
	// 認証トークンの有効期限Unixtimeミリ秒
	ExpiredAt int `json:"expired_at"`

	// 認証トークン
	Token string `json:"token"`
}

// PostV1AuthJSONBody defines parameters for PostV1Auth.
type PostV1AuthJSONBody RequestPostAuth

// GetV1VerifyParams defines parameters for GetV1Verify.
type GetV1VerifyParams struct {
	// トークン
	Token Token `json:"token"`
}

// PostV1AuthJSONRequestBody defines body for PostV1Auth for application/json ContentType.
type PostV1AuthJSONRequestBody PostV1AuthJSONBody
