// Code generated by MockGen. DO NOT EDIT.
// Source: token.go

// Package adapter is a generated GoMock package.
package adapter

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockTokenAdapter is a mock of TokenAdapter interface.
type MockTokenAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockTokenAdapterMockRecorder
}

// MockTokenAdapterMockRecorder is the mock recorder for MockTokenAdapter.
type MockTokenAdapterMockRecorder struct {
	mock *MockTokenAdapter
}

// NewMockTokenAdapter creates a new mock instance.
func NewMockTokenAdapter(ctrl *gomock.Controller) *MockTokenAdapter {
	mock := &MockTokenAdapter{ctrl: ctrl}
	mock.recorder = &MockTokenAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenAdapter) EXPECT() *MockTokenAdapterMockRecorder {
	return m.recorder
}

// Verify mocks base method.
func (m *MockTokenAdapter) Verify(arg0 GetV1VerifyParams, arg1 time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockTokenAdapterMockRecorder) Verify(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockTokenAdapter)(nil).Verify), arg0, arg1)
}
