name: Continuous Integration

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-18.04

    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Unit Test
        run: go test -race -coverprofile="coverage.txt" -covermode=atomic ./...

      - name: upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}